### ISSUE TITLE
Latest build has case-sensitive typo when trying to load config file

### ISSUE THREAD

**Issue by adamdrakon** [VORPCORE/VORP-Housing#19]
> [ script:vorp_housing] Instantiated instance of script VORP.Housing.Shared.BasePluginManager.
> [ script:vorp_housing] Instantiated instance of script VORP.Housing.Shared.Models.House.
> [ script:vorp_housing] Instantiated instance of script VORP.Housing.Shared.Models.Room.
> [ script:vorp_housing] Instantiated instance of script VORP.Housing.Server.HouseInventoryApi.
> [ script:vorp_housing] Instantiated instance of script VORP.Housing.Server.GeneralApi.
> **[ script:vorp_housing] [CRITICAL_ERROR] config.json was not found.**
> [ script:vorp_housing] Instantiated instance of script VORP.Housing.Server.PluginManager.
> [ script:vorp_housing] Instantiated instance of script VORP.Housing.Server.Scripts.Manager.

Resource comes with a `Config.json`, not `config.json`.

**Comment by SimpleSandman** [comment]
Thank you for reporting this!

For now, I'll push a rename to lowercase on all of the config files because of how `LoadResourceFile()` is implemented with case-sensitivity.
```csharp
private const string CONFIG_NAME = "config.json";

string fileContents = API.LoadResourceFile(GetCurrentResourceName(), $"/{CONFIG_NAME}");
```

To prove how the current implementation of `LoadResourceFile()` is over-engineered, on Windows, you can try to create another "Config.json" with a capital "C" and it won't let you as shown below:
![image](https://user-images.githubusercontent.com/14926100/173167616-72a6aba3-ddc4-4c32-a21d-41e696828660.png)
